# Generated by Django 2.1.4 on 2019-06-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
